// examples/vue/counter/Counter.vue
<template>
  <div>
      <h1>{{count}}</h1>
      <div>
        <button @click="increment()" class="button">+</button>
        <button @click="decrement()" class="button">-</button>
      </div>
  </div>
</template>

<script>
import { connect } from '../../../vue';
import { actions } from "./actions";

const mapToProps = ({ count }) => ({ count });

export default {
  data () {
    return {
      count: 0
    }
  },
  created() {
    connect(this, this.$store, mapToProps, actions);
  },
}
</script>

<style>
.button {
    font-size: 20px;
    min-width: 30px;
}
h1 {
    color: #42b983;
}
</style>

// examples/react/counter/src/Counter.js
import React from "react";
import { connect } from "redux-zero/react";

import actions from "./actions";

const mapToProps = ({ count }) => ({ count });

export default connect(mapToProps, actions)(({ count, increment, decrement }) => (
  <div>
    <h1>{count}</h1>
    <div>
      <button onClick={increment}>increment</button>
      <button onClick={decrement}>decrement</button>
    </div>
  </div>
));
